### ISSUE TITLE
torch version > 1.6 stead of >=?

### ISSUE THREAD

**Issue by JudyYe** [princeton-vl/lietorch#2]
Hi Zach, 

Thank you for releasing the code. 
The readme says PyTorch >= 1.6. But when I install w 1.6.0, I got the error 
```
ImportError: cannot import name '_disabled_torch_function_impl'
```

The error goes away for me with pytorch 1.8.1. 
Thanks.

**Comment by zachteed** [comment]
Yes it seems like it isn't working with PyTorch 1.6 anymore, >= 1.7 seems to work, thanks!
